name: Go

on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

      
    - name: Commit and Push to Github
      run: |
          git config --global user.name 'Jeffa-Bob'
          git config --global user.email 'Jeffa-Bob@users.noreply.github.com'
          git commit -am "Update files"
          git config pull.rebase false
          git pull
          git push
